### ISSUE TITLE
data preprocessing and features extraction

### ISSUE THREAD

**Issue by Slasnista** [Stanford-STAGES/sleep-staging#1]
Hello, 

Thank you for sharing your code, I look forward playing with it !

Yet I would like to know: do you plan to release the code to preprocess the data and to extract the features you feed the neural nets with ? You have described a very interesting pipeline in your paper and I would like to investigate it in details.

Thank you in advance.

**Comment by informaton** [comment]
Yes, it should have been included and we are sorry if this is not yet done.  Jens Stephansen is preparing the information and will be posting the weights of the machine learning model etc. to add to GitHub so that people don’t have to retrain the model.

Regarding the data itself,  we cannot release all the sleep studies (many are not ours), but we plan to at least include a subset of 50 control and 20 narcolepsy EDF sleep studies of our own center for people to test the algorithm.

**Comment by informaton** [comment]
The python code for extracting features for the neural nets is provided in our companion repository,  [narcolepsy-detector](https://github.com/Stanford-STAGES/narcolepsy-detector), though some adjustment will need to made to work with your own datasets for now.

**Comment by Slasnista** [comment]
Dear Hyatt,

Thanks a lot for the fast answer. Ok no problem, I will go over the code and see how to use it on my own datasets.

Best regards,
Stanislas Chambon

**Comment by Slasnista** [comment]
Just a quick question, Alexandre Gramfort, my PhD supervisor (cc-ed) noticed that you did not put a license in the repo. Usually, BSD is widely used for python code. 

Which one are you using for these repositories ?

Thanks in advance,
Stanislas Chambon

**Comment by informaton** [comment]
Hi Stanislas,

I recently got confirmation for and posted the software license for the sleep staging portion of the narcolepsy detector.  It is a Creative Commons share alike attribution license, so you can use, modify, and even commercialize the code provided attribution is given to the manuscript source provided.  A link to the full license details is provided in the license.txt file.  

Licensing information for the narcolepsy detection portion, in the Stanford-Stages/narcolepsy-detector repository, is still forthcoming.
